name: Test VSCode extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest
        ]
        node:
          - 18
    steps:
      - name: Set autocrlf to false
        run: git config --global core.autocrlf false
        if: ${{ success() && contains(matrix.os, 'windows') }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Starting Xvfb..."
        shell: bash
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
      - name: Install dependencies
        run: npm ci
      - name: Run test on Ubuntu
        # pretest run compile and lint automatically
        run: npm test
        env:
          DISPLAY: ":99.0"
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
      - name: Run test on ${{ matrix.os }}
        run: npm test
        if: ${{ success() && matrix.os != 'ubuntu-latest' }}
